### ISSUE TITLE
Ensure that the build badge links to an automated build for this repository and not a fork.

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/dlt-daemon#106]
The README has a nice build badge now but clicking on it just shows the image again.
Is this done on a public build server, and is it possible to link the build image to the details page of the actual build?  

Of course, this is very useful in particular if it fails, but also to study what was actually done in a build, whether it is successful or not.

**Comment by gunnarx** [comment]
Actually I notice now that the discussion from #101 might not yet be changed?  I mean making sure that there is an automated build set up for the main repository, not on jardous' fork.  

I believe you can do that in Travis, it is possible that you must make sure your user is part of the GENIVI Organization however (this is just an invite or request needed in GitHub) to be able to see the GENIVI repositories when logged into Travis.

**Comment by ssugiura** [comment]
@gunnarx I finally set up Travis on GENIVI master and fix the link. We can close this.
