### ISSUE TITLE
Dedicated Travis CI instance

### ISSUE THREAD

**Issue by jardous** [GENIVI/dlt-daemon#108]
Currently Travic CI from a fork repo is used (jardous/dlt-daemon). The upstream should have own instance connected to upstream repo and used for building. Link in the README.md has to be updated.

Linked issue: https://github.com/GENIVI/dlt-daemon/issues/42

**Comment by ssugiura** [comment]
@jardous As we set up Travis for GENIVI master, I fixed the link in README.md. We can close this.
