### ISSUE TITLE
gracefully terminate a dlt-client

### ISSUE THREAD

**Issue by frans-fuerst** [GENIVI/dlt-daemon#119]
Maybe I just miss how to do this correctly but trying to terminate a dlt-client results in a SIG32 for me.

In a debugger/IDE this results in messages or popups, on command line I get a warning (while I'm not sure if that's related at all):

    [282850.288472]~DLT~81290~WARNING  ~dlt_user_atexit_handler dlt_user_initialised false

IMHO I'm shutting down the client correctly by calling `DLT_UNREGISTER_CONTEXT` and `DLT_UNREGISTER_APP` before exiting (despite those are called by the exit handler anyway (`dlt_user_atexit_handler`):

    for (auto && context : contexts_) {
      DLT_UNREGISTER_CONTEXT(context.second);
    }
    DLT_UNREGISTER_APP();

Inspecting `dlt_user.c` a bit I found 
`dlt_stop_threads()` call `pthread_cancel` terminating the receiver thread (which itself has no abort-condition).

I also fiddled a bit with `this_thread::sleep_for()` before / after calling `dlt_free()` manually but with no effect.

I'm using `dlt-daemon` / `dlt-client` v2.18 on a recent Linux kernel (5.0.5) on Fedora 29 - and tried v2.16 before with the same result.

Expectation: client terminates gracefully in debugger and stand alone

**Comment by ssugiura** [comment]
Hello @frans-fuerst 
dlt_user_initialised will be set to true in initialization state, and set back to false in case of any errors or atexit_handler is called (dlt_free() is called only from here). Is there any other place where DLT library gives you error message?
BTW, you are talking about an application you developed which is logging using DLT, not client (e.g. DLT Viewer, dlt-receive, etc.), right?

**Comment by ssugiura** [comment]
@frans-fuerst Do you have any update on this?

**Comment by ssugiura** [comment]
@frans-fuerst Friendly reminder.

**Comment by ssugiura** [comment]
@frans-fuerst Please re-open this issue if there's any further problem.
