### ISSUE TITLE
QNX Compile warnings

### ISSUE THREAD

**Issue by maingig** [GENIVI/dlt-daemon#131]
Using the settings detailed in [Issue  #52](https://github.com/GENIVI/dlt-daemon/issues/52)

There are several warnings, the most serious being these:

.../dlt_client.c: In function 'dlt_client_connect':
.../dlt_client.c:263:21: warning: passing argument 2 of 'connect' from incompatible pointer type [-Wincompatible-pointer-types]
                     (struct sockaddr_un *)&addr,
                     ^
In file included from .../dlt_client.c:76:0:
/opt/toolchains/qnx700_gm/target/qnx7/usr/include/sys/socket.h:596:5: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_un *'
 int connect(int, const struct sockaddr *, socklen_t);
     ^
Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_connection.c.o
.../dlt-daemon.c: In function 'dlt_daemon_process_control_connect':
.../dlt-daemon.c:1792:41: warning: passing argument 2 of 'accept' from incompatible pointer type [-Wincompatible-pointer-types]
     if ((in_sock = accept(receiver->fd, &ctrl, &ctrl_size)) < 0) {
                                         ^
In file included from .../dlt-daemon.c:33:0:
/opt/toolchains/qnx700_gm/target/qnx7/usr/include/sys/socket.h:594:5: note: expected 'struct sockaddr * restrict' but argument is of type 'struct sockaddr_un *'
 int accept(int, struct sockaddr * __restrict, socklen_t * __restrict);
     ^
.../dlt-daemon.c: In function 'dlt_daemon_process_app_connect':
.../dlt-daemon.c:1845:41: warning: passing argument 2 of 'accept' from incompatible pointer type [-Wincompatible-pointer-types]
     if ((in_sock = accept(receiver->fd, &app, &app_size)) < 0) {
                                         ^
In file included from .../dlt-daemon.c:33:0:
/opt/toolchains/qnx700_gm/target/qnx7/usr/include/sys/socket.h:594:5: note: expected 'struct sockaddr * restrict' but argument is of type 'struct sockaddr_un *'
 int accept(int, struct sockaddr * __restrict, socklen_t * __restrict);
     ^
.../dlt_client.c:263:21: warning: passing argument 2 of 'connect' from incompatible pointer type [-Wincompatible-pointer-types]
                     (struct sockaddr_un *)&addr,
                     ^
In file included from .../dlt_client.c:76:0:
/opt/toolchains/qnx700_gm/target/qnx7/usr/include/sys/socket.h:596:5: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_un *'
 int connect(int, const struct sockaddr *, socklen_t);
     ^
`

**Comment by ssugiura** [comment]
@maingig Those warnings should be solved in https://github.com/GENIVI/dlt-daemon/commit/40590be05c5eb99f557dfca6f7f6623dcdbe334a. If that's the case, I can plan a new minor release.

**Comment by maingig** [comment]
I saw that change and thought had I tested with it, but it turns out I hadn't.
So yes - it does fix the warnings and a minor release would be appreciated!  Thanks.

**Comment by ssugiura** [comment]
@maingig Thank you for confirmation. Glad to hear that. We will plan a minor release soon.

**Comment by ssugiura** [comment]
@maingig Please note that we released v2.18.3 which includes the commits today.

**Comment by maingig** [comment]
Thank-you!
