### ISSUE TITLE
[Question] Can the library work anywhere as long as the include files exist ?

### ISSUE THREAD

**Issue by Clancys74** [GENIVI/dlt-daemon#138]
Hello,

I want to install this library on a micro-controller (STM32H7) with RTOS.
I saw some RTOS having the POSIX and ANSI standard, would that be enough to use the library as is ?
If not, is it possible for you to tell me the reason why ?

Sincerely,
Clancys74.

**Comment by ssugiura** [comment]
@Clancys74 As we are following POSIX.1-2017, the library should work on those RTOS without any modification.

**Comment by gunnarx** [comment]
@clancys74  Please also report about your success when you have tried this. (Thank you in advance.)

**Comment by ssugiura** [comment]
@Clancys74 Do you have any update?

**Comment by Clancys74** [comment]
Hello,
Sorry for not coming back to you but i was quite occupied lately ^^
I didn't have the pleasure to try to install the DLT on the RTOS as we got a turn-over from the client leading to us stopping this development.
I finally didn't try it and i don't think i will try it anytime soon, i'm really sorry.

At least, i can share my setup :
- RTOS : nuttx (compatible POSIX and ANSI, widely used around the world)
- RTOS : FreeRTOS (partly compatible with POSIX at this time of writing but in development) --> didn't try with it as it is in development but i would have if it was not
- STM32 chip (H7 for me but i would advise to go for the F4 or the F7 - drivers are way more advanced for them in nuttx)

I can't do anything more however so have a good day and good luck :)
Clancys

**Comment by ssugiura** [comment]
@Clancys74 Thanks for the information. It would be helpful in future development. I will close this issue as of now, and we can re-open if this activity comes up again.
