### ISSUE TITLE
No package 'dbus-1' found

### ISSUE THREAD

**Issue by juneJuly** [GENIVI/dlt-daemon#139]
I got an error as below, did i miss any develop lib?
i followed reademe, installed zlib1g-dev libdbus-glib-1-dev.
and i have tried many libs, like libdbus-1-dev...
bye the way, my env:
ubuntu 16.04
cmake 3.12.1

any suggestion？
thank you very much

ERROR MESSAGE:
$ cmake3 .. -DWITH_SYSTEMD=ON -DWITH_SYSTEMD_JOURNAL=ON -DCMAKE_INSTALL_PREFIX=/usr
-- Checking for module 'dbus-1'
--   No package 'dbus-1' found
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FindPkgConfig.cmake:602 (_pkg_check_modules_internal)
  CMakeLists.txt:96 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/path/to/dlt-daemon-2.17.0/build/CMakeFiles/CMakeOutput.log".
See also "/path/to/dlt-daemon-2.17.0/build/CMakeFiles/CMakeError.log".

**Comment by gunnarx** [comment]
Hmm, it should probably be missing libdbus-1-dev but apparently you have tried that... so in that case it's hard to say.  

It could be that pkg-config does not find the relevant files and you need to adjust PKG_CONFIG_PATH or CMAKE_PREFIX_PATH to make cmake find it.

Where are the pkg-config files for D-Bus located?
Do you have:
```
/usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc
```
or
```
/usr/lib/pkgconfig/dbus-1.pc
```
or maybe somewhere else. Try searching:
```
$ find /usr -name dbus-1.pc
```
Can pkg-config run successfully from the shell?  Try running:
```
$ pkg-config --cflags dbus-1
```

**Comment by juneJuly** [comment]
@gunnarx 
thanks for reply

1.FOUND
$ ll /usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc
-rw-r--r-- 1 root root 623 Jun 11 03:46 /usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc

2.NOT FOUND
$ ll /usr/lib/pkgconfig/dbus-1.pc
ls: cannot access '/usr/lib/pkgconfig/dbus-1.pc': No such file or directory

3.of course，find the result of 1
$ find /usr -name dbus-1.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc

4.
$  pkg-config --cflags dbus-1
Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dbus-1' found


i'm donw...
i real have no idea...

**Comment by juneJuly** [comment]
should i config search path of pkg-config?

**Comment by juneJuly** [comment]
well, i think i have solved this by config pkg-config search path as below:
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

just close this issue.

thanks for your help. @gunnarx

**Comment by gunnarx** [comment]
Yes, exactly.  That is the solution I was thinking of, or to use cmake specific variable to do the same. 

Maybe the project should add this pkg-config path since it seems to be used in Ubuntu, which is quite common.  Maintainers, you can consider that (or close the issue)
