### ISSUE TITLE
None of the required 'automotive-dlt;2.17' found

### ISSUE THREAD

**Issue by juneJuly** [GENIVI/dlt-daemon#142]
welll, i got another issue.
i have install dlt-daemon 2.17 from source code,
and th .pc file is at path: 
$ ll /usr/lib/x86_64-linux-gnu/pkgconfig/automotive-dlt.pc
-rw-r--r-- 1 root root 728 Jun 20 20:49 /usr/lib/x86_64-linux-gnu/pkgconfig/automotive-dlt.pc

the file content is as below:
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/automotive-dlt.pc
prefix=/usr
exec_prefix=/usr
libdir=${exec_prefix}/lib/x86_64-linux-gnu
includedir=${exec_prefix}/include

Name: DLT
Description: Diagnostic Log and Trace
Version: 2.17.0
Requires:
Libs: -L${libdir} -ldlt -lrt -lpthread -lz
Cflags: -I${includedir}/dlt -DDLT_2_17

and, i have config pkg-config search path as below:
$ echo $PKG_CONFIG_PATH
/usr/lib/x86_64-linux-gnu/pkgconfig:

but, when i trying to compiler anthoer project, i always got an error as below:
-- Checking for one of the modules 'automotive-dlt;2.17'
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPkgConfig.cmake:659 (message):
  None of the required 'automotive-dlt;2.17' found
Call Stack (most recent call first):
  CMakeLists.txt:57 (pkg_search_module)

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring incomplete, errors occurred!
See also "/path/to/myproject/build/native/log/CMakeFiles/CMakeOutput.log".
See also "/path/to/myproject/build/native/log/CMakeFiles/CMakeError.log".

did i miss something?
i have no idea now

**Comment by votrungchi** [comment]
Hi @juneJuly ,
Its seems you specified the wrong package name in CMake.
It should be 'automotive-dlt' instead of 'automotive-dlt;2.17', or if you want to specified the version, use 'automotive-dlt = 2.17'

**Comment by gunnarx** [comment]
It is written in the message.  It is the same type of error as before.  You now have PKG_CONFIG_PATH in your environment set to one dir. But dlt could be installed somewhere else.

Try some of these:

1. Find the .pc file for automotive-dlt.  
Then make sure cmake can find it:
2. See if you can run pkg-config command in shell for automotive-dlt as mentioned before
3. Remove definition of PKG_CONFIG_PATH.  (Next time try a temporary shell variable instead of environment, an/or use CMAKE specific variable as mentioned.
Or:
4. Add more than one path in PKG_CONFIG_PATH - you just put a : (colon character) to separate them
Example  =/usr/a:/usr/b

**Comment by gunnarx** [comment]
@votrungchi seems to have found the problem. Thanks.

**Comment by ssugiura** [comment]
@juneJuly Do you have any update? Did it solve by the solution from @votrungchi ?

**Comment by juneJuly** [comment]
@ssugiura 
well, 'automotive-dlt = 2.17' not work for me.
i haven't sove this yet.
maybe that is caused by my local enviroment.

**Comment by thanhbnq** [comment]
Hi @juneJuly ,
Just add a note about CMake with DLT. It is for developer note:
https://github.com/GENIVI/dlt-daemon/blob/master/doc/dlt_for_developers.md#dlt-with-cmake
I believe your CMakeList file is doing the same thing.
If not, please share with us the snippet of CMakeList which contains DLT part.

**Comment by ssugiura** [comment]
@juneJuly Any update? Were you able to solve this?

**Comment by ssugiura** [comment]
@juneJuly I will close this as there's no further comment. Please re-open if any issue still remains.
