### ISSUE TITLE
id changed I don't know

### ISSUE THREAD

**Issue by jinsheng20** [GENIVI/dlt-daemon#150]
![微信截图_20190725172622](https://user-images.githubusercontent.com/12907063/61863035-6ffa1800-af01-11e9-9bd5-dc6e9129bfb7.png)
I want to make this id larger, how to modify it

**Comment by ssugiura** [comment]
@jinsheng20 This comes from message counter (mcnt) of DLT header and is 1 byte, which we follow the requirement in AUTOSAR Log and Trace Protocol Specification.
> [PRS_Dlt_00319] ⌈The Message Counter is an unsigned 8-bit (0-255) integer. ⌋ (RS_LT_00018)

**Comment by jinsheng20** [comment]
Thanks!  
Does the dlt-viewer display because it is being processed?

**Comment by ssugiura** [comment]
@jinsheng20 I believe so. Although it's not clearly mentioned in dlt-viewer documents, it should also follow AUTOSAR protocol.

**Comment by jinsheng20** [comment]
Thanks!
