### ISSUE TITLE
 DLT_USER_BUF_MAX_SIZE limitation in dlt_user.h

### ISSUE THREAD

**Issue by mohammadrasekh68** [GENIVI/dlt-daemon#156]
hello
we are currently using DLT logging system for our C++ application and for navigation purposes we are depending on __PRETTY_FUNCTION__ C++ macro.
problem rises when we have several layer classes. in that case, some times buffer size reaches and nothing is logged( even 1390 first characters)
is there a way to increase the size of this buffer or a way around this problem?
Regards
Rasekh 
#dlt_user.h 
#116

**Comment by ssugiura** [comment]
@mohammadrasekh68 I would be solved with the pull request https://github.com/GENIVI/dlt-daemon/pull/157. Could you try with the patch?

**Comment by mohammadrasekh68** [comment]
but this will not solve the issue, this will just give us the possiablity not to lose the first 1390char, but we wont be able to extend this buffer.

**Comment by votrungchi** [comment]
@mohammadrasekh68 You can use the **DLT_LOG_MSG_BUF_LEN** environment variable to overwrite the default buffer size. e.g. export DLT_LOG_MSG_BUF_LEN=2048
