### ISSUE TITLE
QNX build fails on 2.18.4

### ISSUE THREAD

**Issue by maingig** [GENIVI/dlt-daemon#169]
.../dlt_daemon_udp_common_socket.h:37:23: fatal error: sys/epoll.h: No such file or directory

**Comment by ssugiura** [comment]
@maingig Thanks for pointing out. If you are not using UDP feature, could you please set WITH_UDP_CONNECTION to OFF in cmake option or take https://github.com/GENIVI/dlt-daemon/commit/c9d1ba4b522afb79a719daea9e421724299f197f as code base? In the meantime we will try to fix it soon.

@Sunil-K-S FYI

**Comment by ssugiura** [comment]
@maingig We fixed that issue with https://github.com/GENIVI/dlt-daemon/commit/b55972cd33df6e02ffcefcb577fbb83fb72b2ef8. Please open this issue if there's any further problems.
