### ISSUE TITLE
EINTR dlt-daemon do not deal with

### ISSUE THREAD

**Issue by chenlimingcn** [GENIVI/dlt-daemon#172]
EINTR dlt-daemon do not deal with
I think this is very import ,
but the current version do not deal with this signal(EINTR)

**Comment by ssugiura** [comment]
@ssugiura Sorry for my late reply and thanks for pointing this out. We will look into this soon. Or it's very welcome if you already have some suggestion.

**Comment by votrungchi** [comment]
Hello @chenlimingcn , Based on the man page [1], EINTR is about Interruption of system calls and library functions by signal handlers
       If a signal handler is invoked while a system call or library
       function call is blocked, then either:
       * the call is automatically restarted after the signal handler
         returns; or
       * the call fails with the error EINTR.
In case of the call fails with the error EINTR, it also return the error (-1), so currently, dlt-daemon handling it as abnormal cases.
So could you please help to give some detail suggestion or an example in dlt-daemon source code that need to deal with the EINTR?
We very appreciate it.
[1] http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by ssugiura** [comment]
@chenlimingcn , Please refer to the comment from @votrungchi and let us know your opininon.

**Comment by ssugiura** [comment]
@chenlimingcn Please re-open this issue if there's any further comment.
