### ISSUE TITLE
epoll is not supported by qnx, dlt-daemon compile failed.

### ISSUE THREAD

**Issue by saitamo** [GENIVI/dlt-daemon#183]
version:2.18.4
OS: QNX7.0
The log is as follows:
/home/jzhang61/core/log/LogManager/dlt-daemon-2.18.4/src/daemon/udp_connection/dlt_daemon_udp_common_socket.h:37:23: fatal error: sys/epoll.h: No such file or directory
compilation terminated.
src/daemon/CMakeFiles/dlt-daemon.dir/build.make:494: recipe for target 'src/daemon/CMakeFiles/dlt-daemon.dir/udp_connection/dlt_daemon_udp_socket.c.o' failed
make[2]: *** [src/daemon/CMakeFiles/dlt-daemon.dir/udp_connection/dlt_daemon_udp_socket.c.o] Error 1
CMakeFiles/Makefile2:209: recipe for target 'src/daemon/CMakeFiles/dlt-daemon.dir/all' failed
make[1]: *** [src/daemon/CMakeFiles/dlt-daemon.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by votrungchi** [comment]
Hi @saitamo This issue has been fixed on latest master ( pull request #177 ). Could you please give it a try?

**Comment by saitamo** [comment]
ok, compile success, Thanks!
