### ISSUE TITLE
After setting trace to 0 with dlt-control, logs are still visible in dlt-viewer

### ISSUE THREAD

**Issue by AdrianStoenescu** [GENIVI/dlt-daemon#193]
If I use **dlt-control -r 0 -uv**, -> set all traces to 0.
This can be confirmed by: **dlt-control -juv** and indeed all traces are set to 0.
But the logs are still visible in dlt-viewer. Shouldn't the logs be disabled at this point?

In the same scenario but using logLevel instead of Trace state we get the following:
**dlt-control -l 0 -uv** -> set all log levels to 0.
Logs are correctly set to 0, confirmed by **dlt-control -juv**.
At this point, logs are no longer visible in dlt-viewer, so for logLevel we get the expected behavior but not the same behavior when using trace state.

**Comment by ssugiura** [comment]
Actually trace status is used if a trace message should be send or not. So it's not that you can disable the log message in the client. You can refer to [PRS_Dlt_00619] and [PRS_Dlt_00620] in AUTOSAR spec (https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-0/AUTOSAR_PRS_DiagnosticLogAndTraceProtocol.pdf).
Note: This is an old specification as we follow 4.0 of AUTOSAR spec right now, but I feel this one has more clear explanation.
