### ISSUE TITLE
[Question] dlt-system new feature

### ISSUE THREAD

**Issue by sebastienraillet** [GENIVI/dlt-daemon#195]
Hi all,

I would like to propose a modification inside dlt-system which adds a new feature. This new feature allows dlt-system to completely replace syslogd.
Instead of having syslogd running + dlt-system running, we have only dlt-system which is running (means one less application on the system).
This work on my side should be a little adapted to be cleanly up streamed.
It's why I ask you here if you're interested by such kind of new feature or if it's something you consider not very useful knowing that, currently, dlt-system can catch the log of syslogd through the UDP socket.

Thanks in advance for your answer.
Sébastien

**Comment by ssugiura** [comment]
@sebastienraillet Sorry for my late reply. It's a very interesting feature to reduce a duplicate work on the system. If you already have the work, please kindly share us. Thanks!

**Comment by ssugiura** [comment]
@sebastianlipponer I will close this issue and discuss further in PR if you could raise it. If you need to discuss anything beforehand, please reopen this issue. Thanks!
