### ISSUE TITLE
How to write a filter which can store all logs?

### ISSUE THREAD

**Issue by bssung** [GENIVI/dlt-daemon#198]
[FILTER1]
LogAppName=.*
ContextName=.*
...

When I write a filter like this, I can't store any logs. 
I want to store all logs in offline storage, so I must add filter in dlt_logstorage.conf, but it seems filter can't support store logs of all apps and contexts. 

Can anyone give me some suggestion?

**Comment by ssugiura** [comment]
@bssung You can specify EcuID to use wildcards for both LogAppName and ContextName.

**Comment by bssung** [comment]
@ssugiura Thank you!  
I don't kown how to specify EcuID with wildcard... 
Excuse me, can you show me an example filter? 
[FILTER2]
LogAppName=TEST, LOG
ContextName=.*
LogLevel=DLT_LOG_ERROR
File=Test
FileSize=250000
NOFiles=5
EcuID=ECU1
SyncBehavior=ON_SPECIFIC_SIZE
SpecificSize=5000

**Comment by ssugiura** [comment]
@bssung We could verify it works when you remove both LogAppName and ContextName sections and add EcuID. Could you try that?

**Comment by bssung** [comment]
@ssugiura  I removed LogAppName and ContextName, it works well now.  
Thanks for your help.

**Comment by ssugiura** [comment]
You're welcome. We will update logstorage document accordingly.
