### ISSUE TITLE
[Question]Why the Process will create two high priority child threads? 

### ISSUE THREAD

**Issue by WOXINGYANG** [GENIVI/dlt-daemon#202]
A process using the DLT will create two child threads. Why are these two child threads prioritized so high?Can we modify these two threads' priority?

**Comment by ssugiura** [comment]
@WOXINGYANG Sorry for my late reply. Currently thread priority is not configurable. I can understand that those kind of feature is pretty nice to have, but we don't have much time to implement them. If you would like to introduce them, could you raise a PR?

**Comment by ssugiura** [comment]
@WOXINGYANG This is a friendly reminder. Would you like to discuss further on this topic?

**Comment by ssugiura** [comment]
@WOXINGYANG Any update on this?

**Comment by ssugiura** [comment]
I will close this issue since there is no update for more than half a year. Please raise PR if any change proposal is available. Thank you!
