### ISSUE TITLE
[QUESTION] Is there a way to ping the daemon from the user?

### ISSUE THREAD

**Issue by cogle** [GENIVI/dlt-daemon#203]
I am wondering if there is a way in which I can ping the daemon from a user to see if it alive. I have a user application that in the case where the daemon is unreachable I want to store the log message elsewhere and not in a buffer managed by the dlt-user. 

```
        DltContext context;
        DLT_REGISTER_CONTEXT(context, "Test", "Examle");

        DltContextData log_local;
        DltReturnValue dlt_local_ret;

        dlt_local_ret = dlt_user_log_write_start(&context, &log_local, DLT_LOG_INFO);
        if (dlt_local_ret != DLT_RETURN_TRUE) {
            std::cout << "Log write start failed" << std::endl;
        }


        const std::string sample_message = "Testing this";
        dlt_user_log_write_string(&log_local, sample_message.c_str());
        dlt_local_ret = dlt_user_log_write_finish(&log_local);

        if (dlt_local_ret != DLT_RETURN_OK) {
            std::cout << "Log write finish failed" << std::endl;
        }

        DLT_UNREGISTER_CONTEXT(context);
```

In the above call I would have expected the `dlt_user_log_write_finish` to return a failure value but it returns DLT_RETURN_OK since after failing to connect to the dlt-daemon it writes the message to the internal buffer and then propagates the value of this return to the user, and not that the communication with the dlt-daemon failed. 
I am wondering if there is a way to short circuit this and check before the `dlt_user_log_write_start` to see if there is communication with the `dlt-daemon` and then proceed to log the message.

**Comment by ssugiura** [comment]
@cogle Sorry for my late reply. We don't have any way to check the communication between daemon and library. If you would like to introduce the feature, could you please raise a PR? In my opinion, it can be done by either
- Add a cmake option to enable/disable ring buffer storage
- Add an interface to see the ring buffer size

**Comment by cogle** [comment]
Currently I check the ring buffer size and that is sufficient if I have time I will consider creating a PR to add in the aforementioned feature.

I have one more question, if the dlt-viewer updates the log level for a specific context does the dlt-daemon forward this log-level to the context in the dlt-user or do I need to explicitly listen to the `log_level_changed_callback`, in order to be aware of any changes to the log-level.

**Comment by ssugiura** [comment]
> Currently I check the ring buffer size and that is sufficient if I have time I will consider creating a PR to add in the aforementioned feature.
Thank you. That would be really helpful.

> I have one more question, if the dlt-viewer updates the log level for a specific context does the dlt-daemon forward this log-level to the context in the dlt-user or do I need to explicitly listen to the log_level_changed_callback, in order to be aware of any changes to the log-level.
No, you don't have to listen by log_level_changed_callback(). The daemon and dlt-user would take care of changing the log level in dlt-user. If you want to do something when the level changed, then you should use the function. Please refer to the implementation of dlt-example-user for an example.

**Comment by cogle** [comment]
Thanks I was just confirming. I will close this issue and look into creating a `ping` feature.
