### ISSUE TITLE
Is there any interfaces for user application to check whether it connected to dlt-daemon?

### ISSUE THREAD

**Issue by bssung** [GENIVI/dlt-daemon#207]

**Comment by bssung** [comment]
I'd like to know,, is my user applicaion connected succesfully to dlt-daemon. 
Is there any kind of functions like IS_CONNECT_OK( )?

**Comment by thanhbnq** [comment]
Hi @bssung ,
I would say that there is no such an interface at the moment.
libdlt is trying to wrap-up and take care of all interactions between user application and dlt-daemon.
Could you please tell me which use case you are concerning about the connection's status between application and daemon?

**Comment by bssung** [comment]
@thanhbnq 
I was concerning if the connection is lost, application can't send log to deamon. 
I hope I can know this situation in my application and stop sending logs.

**Comment by thanhbnq** [comment]
Hi @bssung ,
If user application loses connection to dlt-daemon, libdlt will push the dlt log message to buffer until its' maximum size is reached. And in libdlt, there is a feature to reattach and then resend dlt message in buffer to daemon in case of disconnection.
If reattachment fails, there won't be no resend then.
I think it could satisfy your concern, couldn't it?

**Comment by cogle** [comment]
This is similar to an issue I asked #203

**Comment by bssung** [comment]
Thanks @cogle,
May I ask how you check the ringbuffer size, and where is the point to add the code?

**Comment by cogle** [comment]
```
        int before_size     = 0;
        int before_capacity = 0;
        dlt_user_check_buffer(&before_capacity, &before_size);
        // LOG 
        int after_size     = 0;
        int after_capacity = 0;
        dlt_user_check_buffer(&after_capacity, &after_size);

        if (after_size > before_size) {
        // Logging failed
        }

```

**Comment by bssung** [comment]
@cogle Thank you very much : )
