### ISSUE TITLE
In the DLT Daemon who is responsible for filtering log messages ?

### ISSUE THREAD

**Issue by cogle** [GENIVI/dlt-daemon#209]
I have question regarding logging levels. I know that the DLT user will check if the message being sent out is a level that should be logged out. I am wanting to confirm that the filtering of log levels is the sole responsibility of the DLT user. 

In addition I have a question in the instance where one is using offline storage and the configuration is something like 

```
[FILTER1]
LogAppName=APP1
ContextName=CON1,CON2
LogLevel=DLT_LOG_DEBUG
File=App
FileSize=10000
NOFiles=10
```

and the default logging level in the `dlt.conf` is `DLT_LOG_INFO` will the DLT daemon set `APP1`'s log level to `DLT_LOG_DEBUG` ? 

One more question does the above filter only write out `DLT_LOG_DEBUG` messages ?

**Comment by ssugiura** [comment]
@cogle Sorry for my late reply.
> I am wanting to confirm that the filtering of log levels is the sole responsibility of the DLT user.
DLT user is the one who is responsible to filter the DLT messages depending on log level. 
> the default logging level in the `dlt.conf` is `DLT_LOG_INFO` will the DLT daemon set `APP1`'s log level to `DLT_LOG_DEBUG` ?
Yes, that is correct. LogStorage log level setting as a highest priority, so it will be updated to `DLT_LOG_DEBUG` for this case.
> One more question does the above filter only write out `DLT_LOG_DEBUG` messages ?
No, it will write out lower level than `DLT_LOG_DEBUG`, means all messages expect `DLT_LOG_VERBOSE`.

**Comment by cogle** [comment]
No worries @ssugiura, thank you for your reply and clarifications.

I am wondering if I specify `DLT_LOG_DEBUG` is there anyway to log out `DLT_LOG_DEBUG` messages to a file exclusively currently. In my case I am only worried about logs at this level exclusively.

**Comment by ssugiura** [comment]
@cogle Unfortunately, no. DLT Offline Logstorage can only filter out the ones below specified log level, not above. If any client e.g. DLT Viewer is available, then you can use a filter to log only specified log level.

**Comment by Manojcv55** [comment]
@ssugiura  , In DLT offline log storage , what does on_demand sync strategy means .

**Comment by thanhbnq** [comment]
@Manojcv55  if that strategy is applied, the offline log storage messages will be stored in the cache then they will be written to offline file when receive the control message via command:

> dlt-logstorage-ctrl -s

**Comment by Manojcv55** [comment]
I have a question in the instance where one is using offline storage and the configuration is something like

[FILTER1]
LogAppName=APP1
ContextName=CON1,CON2
LogLevel=DLT_LOG_INFO
File=App
FileSize=10000
NOFiles=10
and the default logging level in the dlt.conf is DLT_LOG_INFO , All the logs in dlt-viewer is info 
But if i changed the log level through dlt-viewer it is not updating in the viewer ?
Is this an expected behavior?

**Comment by cogle** [comment]
@ssugiura Thanks the reply, sorry for the late response. 
I was double checking because I knew that was how the DLT Viewer filtered out logs and was wondering if the DLT Daemon's implementation also supported that feature.

**Comment by ssugiura** [comment]
@Manojcv55 Yes, that is a correct behavior. DLT takes up the log level defined in Logstorage as highest priority.
