### ISSUE TITLE
No package 'automotive-dlt' found

### ISSUE THREAD

**Issue by Sabita05** [GENIVI/dlt-daemon#210]
Facing the below issue while trying to compile the given example as it says " No package 'automotive-dlt' found"

root@am57xx-evm:~/dlt/example/build# cmake ..
-- Checking for module 'automotive-dlt'
--   No package 'automotive-dlt' found
CMake Error at /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPkgConfig.cmake:602 (_pkg_check_modules_internal)
  CMakeLists.txt:28 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/root/dlt/example/build/CMakeFiles/CMakeOutput.log"

**Comment by ssugiura** [comment]
@Sabita05 Your error message already tells you what you need:); it needs automotive-dlt. It can be built by enabling WITH_DLT_PKGCONFIG.

**Comment by Sabita05** [comment]
@ssugiura ,I tried building with the above option but,I am still facing the same issue.
I am trying to build it on AM571x board.

It works perfectly fine on ubuntu PC.

**Comment by ssugiura** [comment]
@Sabita05 Is automotive-dlt.pc available on your build environment, or you're having trouble installing the pkgconfig in first place?

**Comment by ssugiura** [comment]
@Sabita05 Any update on this?

**Comment by ssugiura** [comment]
Closing the issue since there's no update for long time. @Sabita05 Please reopen this issue if it's not solved and you still need any help. Thanks!
