### ISSUE TITLE
Log output level control

### ISSUE THREAD

**Issue by smallert** [GENIVI/dlt-daemon#211]
The DLT log output level is not controlled when the process starts.Logs above the default level will be output. This occurs when a process connects to DLT-daemon and returns to normal after a short time.The test mode is serial port output.

**Comment by ssugiura** [comment]
@smallert Does following note in `dlt_for_developers.md` under doc help you, or is it a different behavior?
```
Note: Please be aware that it might be taken up to a second until the
synchronization of loglevel between DLT Daemon and application is done.
```

**Comment by ssugiura** [comment]
@smallert This is a friendly reminder. Is the issue solved by above note, or is it a different issue?

**Comment by smallert** [comment]
Thank you for your answer. Applying LOG output 1 second after connecting to DLT daemon can solve the above problem.But it's not a very good solution for me.For multithreaded processes, a delay of 1 second has a significant impact on the overall processing logic.

**Comment by smallert** [comment]
I pulled the latest DLT source code and compiled it, and found that the path of the DLT configuration file is my compilation path by default. Is there any way to change the path of the configuration file without recompiling?

**Comment by ssugiura** [comment]
@smallert Thanks for your verification. I totally agree with your opinion. But unfortunately we couldn't come up with any good design to prevent this, so as of now we made it as a limitation.
