### ISSUE TITLE
does  this dlt-daemon support android platform

### ISSUE THREAD

**Issue by huangkai103** [GENIVI/dlt-daemon#212]
It seems  mqueue.h could not be found on android ndk.
Compilation error are as flows,
----------------------------cmake release----------------------------
-- Check for working C compiler: /home/host/work/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/host/work/android-ndk-
[build_error.txt](https://github.com/GENIVI/dlt-daemon/files/4311485/build_error.txt)
r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/host/work/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/host/work/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not defined. Using default build type 'RelWithDebInfo'.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
.......
.......
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DEBUG

-- Build files have been written to: /home/host/work/dlt-daemon-master/build
Scanning dependencies of target dlt
[  1%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_user.c.o
In file included from /home/host/work/dlt-daemon-master/src/lib/dlt_user.c:62:
/home/host/work/dlt-daemon-master/include/dlt/dlt_user.h:76:13: fatal error: 'mqueue.h' file not found
#   include <mqueue.h>
            ^~~~~~~~~~
1 error generated.
src/lib/CMakeFiles/dlt.dir/build.make:62: recipe for target 'src/lib/CMakeFiles/dlt.dir/dlt_user.c.o' failed
make[2]: *** [src/lib/CMakeFiles/dlt.dir/dlt_user.c.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'src/lib/CMakeFiles/dlt.dir/all' failed
make[1]: *** [src/lib/CMakeFiles/dlt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_user.c.o
In file included from /home/host/work/dlt-daemon-master/src/lib/dlt_user.c:62:
/home/host/work/dlt-daemon-master/include/dlt/dlt_user.h:76:13: fatal error: 'mqueue.h' file not found
#   include <mqueue.h>
            ^~~~~~~~~~
1 error generated.
src/lib/CMakeFiles/dlt.dir/build.make:62: recipe for target 'src/lib/CMakeFiles/dlt.dir/dlt_user.c.o' failed
make[2]: *** [src/lib/CMakeFiles/dlt.dir/dlt_user.c.o] Error 1

**Comment by ssugiura** [comment]
@huangkai103 We already have a fix locally. We will post it soon.

**Comment by michiwend** [comment]
Hi @ssugiura. I ran into the same problem when trying to build the project on macos since macos doesn't support POSIX message queues. The fix you mentioned... will this remove the dependency to mqueue.h and will I be able to build the project on macos afterwards or am I on the wrong track anyway?

**Comment by ssugiura** [comment]
@michiwend My idea is to add new cmake option to enable/disable network trace feature. At the beginning I wanted to check dependency with cmake by CHECK_INCLUDE_FILES and CHECK_FUNCTION_EXISTS, but found out that it might break dependency with other components which uses DLT. So cmake option was the better choice and I'm on my way for the improvement.

**Comment by michiwend** [comment]
@ssugiura cool, thank you for the update. I will try it out w/o the trace feature as soon as your change is pushed 👍

**Comment by ssugiura** [comment]
@michiwend After some verification, I went this the solution
> to check dependency with cmake by CHECK_INCLUDE_FILES and CHECK_FUNCTION_EXISTS,
So no new cmake option will be added. We will raise a PR very soon. Thank you for your patience!

**Comment by anamikasinghcnh** [comment]
@ssugiura is the fix already pushed for this issue?
I am facing the same problem for androd-ARM build of dlt-daemon
/dlt-daemon/include/dlt/dlt_user.h:76:23: fatal error: mqueue.h: No such file or directory
is there any work around available if not pushed yet!

**Comment by ssugiura** [comment]
@huangkai103 @michiwend @anamikasinghcnh I'm very sorry that we couldn't update very soon. With latest commits we've merged, it should be possible to compile on Android too. Please check and raise another issue if there's any problem.
Thank you!
