### ISSUE TITLE
NWTSegmented: Error while reading queue: Bad file descriptor in dlt_user_trace_network_segmented_thread

### ISSUE THREAD

**Issue by RudiSV** [GENIVI/dlt-daemon#213]
If dlt_segmented_queue_read_handle is not initialized and dlt_user_trace_network_segmented_thread is canceled, mq_receive call results in "Bad file descriptor" error.

...

[----------] Global test environment tear-down
[==========] 236 tests from 39 test cases ran. (3826999 ms total)
[  PASSED  ] 236 tests.
[  501.752852]~DLT~ 2074~WARNING  ~NWTSegmented: Error while reading queue: Bad file descriptor

**Comment by RudiSV** [comment]
[FIX-prevent-usage-of-uninitialized-message-queue-han.patch.txt](https://github.com/GENIVI/dlt-daemon/files/4318183/FIX-prevent-usage-of-uninitialized-message-queue-han.patch.txt)

**Comment by ssugiura** [comment]
@RudiSV Thanks for pointing out. As you already have a patch to fix the issue, I propose to raise a PR instead.

**Comment by RudiSV** [comment]
Duplicate, #214
