### ISSUE TITLE
DLT Offline Logstorage wild card 

### ISSUE THREAD

**Issue by karthikshanmugam** [GENIVI/dlt-daemon#220]
Hi,

The below filter does not log any messages.

[FILTER1]
LogAppName=.*
ContextName=.*
LogLevel=DLT_LOG_INFO
File=example
FileSize=50000
NOFiles=5

I can't give wildcards to both app and context name, even if I add EcuId it does not help.
Is there a way to log messages with wildcards for both app and context?

Best regards,
Karthik

**Comment by ssugiura** [comment]
@karthikshanmugam This issue is the same as https://github.com/GENIVI/dlt-daemon/pull/216. We will give a solution soon.

**Comment by karthikshanmugam** [comment]
Thank you :-)

**Comment by ssugiura** [comment]
@karthikshanmugam I'm very sorry that we couldn't update very soon. With latest commits we've merged, it should be possible to use wildcards to both app and context name if Ecu ID is specified. Please check and raise another issue if there's any problem.
Thank you!
