### ISSUE TITLE
DLT File Transfer plugin does not show received files

### ISSUE THREAD

**Issue by karthikshanmugam** [GENIVI/dlt-daemon#224]
Hello,

I can't seem to get the file transfer plugin working. I can see the file in the log, but the plugin interface shows nothing.

![image](https://user-images.githubusercontent.com/104696/80334980-8bb79380-8870-11ea-9616-83f7f48c5754.png)

**Comment by ssugiura** [comment]
@karthikshanmugam I haven't tested yet, but is this an issue in DLT Viewer or in Daemon? Could you please isolate this point?

**Comment by karthikshanmugam** [comment]
@ssugiura  Not sure if the issue is in daemon as you can see the file transfer header and data in the logger. Must be an issue in the viewer or the plugin.

**Comment by ssugiura** [comment]
@karthikshanmugam If it's an issue in DLT Viewer, I would propose to raise an issue in dlt-viewer github as we don't support it.

**Comment by funcode2** [comment]
How does your dlt_filetransfere.conf look like? What command do you use to transfer the file? Did you specify the pid and cid properly? Also, the file you send must be binary file. That means you can't send the original dlt log file.
-Josh

**Comment by karthikshanmugam** [comment]
hi @funcode2 

Yes, the file is a binary file. 
I'm using the APIs to transfer the file like below and I don't have any dlt-filetransfer.conf in the system.

```
 static int32_t DltIf_Send( char *file )
 {
    int32_t ret = RM_FAILED;

    if( 0 == dlt_user_log_file_infoAbout( &rm_ctx, file ) )
    {
        if( 0 == dlt_user_log_file_complete( &rm_ctx, file, DELETE_FILE, TIMEOUT ) )
        {
            ret = RM_OK;
        }
    }

    return ret;
 }
```

**Comment by funcode2** [comment]
You can try manually send the binary file from your device to dlt-viewer. The filetransfer.conf can be used in dlt-viewer plugin. Then you get the feel on how it should look like.

Sample filetransfer.conf.
<?xml version="1.0" encoding="UTF-8"?>
<filetransferplugin_configuration>
<TAG_FLST>FLST</TAG_FLST>
<TAG_FLDA>FLDA</TAG_FLDA>     
<TAG_FLFI>FLFI</TAG_FLFI>     
<TAG_FLER>FLER</TAG_FLER>     
<TAG_FLAPPID>FLTR</TAG_FLAPPID>                 
<TAG_FLCTID>FLTR</TAG_FLCTID>   
 </filetransferplugin_configuration>

from you device, just execute "dlt-example-filetransfer -a FLTR -c FLTR filename" so you can observe the dlt-viewer to receive the file.

**Comment by ssugiura** [comment]
@karthikshanmugam Do you have any update? Are you still facing the issue?

**Comment by funcode2** [comment]
Thanks for the follow up. It works fine now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ssugiura** [comment]
@funcode2 Thanks for quick reply! Then I will close this issue.
