### ISSUE TITLE
Default vs predefined LL TS

### ISSUE THREAD

**Issue by baduras** [GENIVI/dlt-daemon#226]
When a context is registered with predefined log level (trace status) using dlt_register_context_ll_ts, then by default configured values for log level trace status (configured from client or in dlt.conf file) are ignored.
Is this expected behavior? What actually means in this context predefined?

**Comment by ssugiura** [comment]
@baduras Yes, it is an expected behavior. Please take a look into "Methods to set the log level for applications and contexts" section in doc/dlt_for_developers.md.

> - Application registers itself at daemon with self-defined log level
    - In this case no log level is set by the daemon but by the application
      itself.
    - This happens when the application registers itself with
      `DLT_REGISTER_CONTEXT_LL_TS()` or `dlt_register_context_ll_ts()`

**Comment by baduras** [comment]
Thanks for info.

**Comment by baduras** [comment]
Not an issue
