### ISSUE TITLE
 DLT configuration file path

### ISSUE THREAD

**Issue by smallert** [GENIVI/dlt-daemon#227]
I pulled the latest DLT source code and compiled it, and found that the path of the DLT configuration file is my compilation path by default. Is there any way to change the path of the configuration file without recompiling?

**Comment by ssugiura** [comment]
@smallert Speaking of installation path of the configuration file, it can be changed by setting expected path to CMAKE_INSTALL_PREFIX. There is no way to change the installation path without recompiling.
If it's about where dlt-daemon finds the file, you can give the expected path to the daemon by -c option.

**Comment by smallert** [comment]
I used dlt-control, and the error log it output was unable to find the configuration file, because my current configuration file path is different from my compile path, so dlt-control cannot be used.Can you specify a configuration file path for DLT -control?

**Comment by ssugiura** [comment]
@smallert Could you paste the exact log message output and option you have to dlt-control?

**Comment by smallert** [comment]
# dlt-control -l 4 -u 127.0.0.1
Cannot open configuration file: /disk3/workspace/work/dlt-daemon-master-v2.18/build/install/etc/dlt.conf
Cannot open configuration file: /disk3/workspace/work/dlt-daemon-master-v2.18/build/install/etc/dlt.conf
ERROR: Failed to read ECUId from dlt.conf
dumping to /debug/dlt-control.core
thread 1.flags is 0x200001
thread 1 was SIGNALLED
thread 1.why is 0x1
Similar to the above, controlling log level output using dlt-control results in a crash of the dlt-control process

**Comment by ssugiura** [comment]
@smallert Thanks. This gives me a better hint. You can specify ECUId by giving -e option to dlt-control then you can avoid configuration file parsing. The ECUId should be the same as dlt.conf.

**Comment by smallert** [comment]
Thank you for your proposal
# dlt-control -l 4 -e ECU1 -u 127.0.0.1
Cannot open configuration file: /disk3/workspace/work/dlt-daemon-master-v2.18/build/install/etc/dlt.conf
unlinking old /debug/dlt-control.core
dumping to /debug/dlt-control.core
Can't avoid configuration file parsing.

**Comment by smallert** [comment]
What else do I need to specify to avoid parsing configuration files?

**Comment by ssugiura** [comment]
@smallert Ah, sorry. Missed one more point. Could you get rid of -u option and use TCP?

**Comment by smallert** [comment]
Thanks for your answer. I can't get rid of the -u option.When I use dlt-control, I have to specify -u.My understanding is that the -u option will indicate which dlt-daemon to connect to. Dlt-control and dlt-daemon do not communicate over the network, so what does this have to do with TCP?

**Comment by smallert** [comment]
# dlt-control
ERROR: No hostname selected
Usage: dlt-control [options] hostname/serial_device_name
Send control message to DLT daemon.
DLT Package Version: 2.18.4 STABLE, Package Revision: , build on Apr 14 2020 10:35:16
-SYSTEMD -SYSTEMD_WATCHDOG -TEST -SHM

**Comment by ssugiura** [comment]
@smallert dlt-control communicates over socket or tcp (or serial). So you just need to `dlt-control <whatever> 127.0.0.1` as written in usage, if 127.0.0.1 is the IP which dlt-daemon is running on (or maybe just localhost? Depends on your environment). If you use -u, it will connect to dlt-daemon via socket, which is defined in dlt.conf, means we cannot avoid reading dlt.conf to that path.

**Comment by smallert** [comment]
Thanks for your answer. I'll think about it again
