### ISSUE TITLE
dlt_common:clear buffer when overflow in dlt_buffer_get

### ISSUE THREAD

**Issue by foobaa** [GENIVI/dlt-daemon#229]
In commit 
https://github.com/GENIVI/dlt-daemon/pull/215/commits/98f980ee5b89622f2e0fa3e2effff15ab8fb2891

The buffer was not reset

**Comment by ssugiura** [comment]
@foobaa Thank you for pointing out. We have tested also and could see that reset is not happening. Also some tests are failing due to the change. I will revert the change for now.

@ricleite , @jardous , FYI. This comes from PR https://github.com/GENIVI/dlt-daemon/pull/215

**Comment by ricleite** [comment]
It is my oversight, sorry.

Although I don't understand the revert instead of just adding `dlt_buffer_reset(buf);`. The revert reintroduces an overflow, one that leads to occasional and hard-to-debug segfaults.

**Comment by foobaa** [comment]
Please add a testcase to justify the change please. @ricleite 

@ssugiura can you also mention the regression you saw with the earlier commit of returning ERROR

Personally, it's confusing to see commits being made without addition of proper testcases, which justifies the change of the commit.
