### ISSUE TITLE
Log level update

### ISSUE THREAD

**Issue by baduras** [GENIVI/dlt-daemon#236]
Could you confirm this is expected behavior:
 - when offline log storage to filter set of APPIDs for log level e.g. DLT_LOG_ERROR is configured
- and default log level is set to e.g. DLT_LOG_INFO

What log level should be configured in usercontext?  
I would expect DLT_LOG_INFO, but current implementation sets DLT_LOG_ERROR.

See source:

```
if (context->storage_log_level != DLT_LOG_DEFAULT)
        usercontext.log_level = context->log_level >
            context->storage_log_level ? context->log_level : context->storage_log_level;
else /* Storage log level is not updated (is DEFAULT) then  no device is yet connected so ignore */
        usercontext.log_level =
            ((context->log_level == DLT_LOG_DEFAULT) ? daemon->default_log_level : context->log_level);
```

When context->log_level is default -> -1 then there is forced log level from offline log storage to be used and not the default log level (which I would expect).

**Comment by ssugiura** [comment]
@baduras Current DLT Daemon is designed and implemented as so. The daemon consider Logstorage log level as highest priority.
Workaround for this is to set the appropriate log level for each application in e.g. DLT Viewer side and it will be changed from default to verbose so it will work as your expectation.

**Comment by baduras** [comment]
Thank you for answer. The dlt-daemon  is designed and implemented this way, but is it lets say "expected or required" behavior?

**Comment by ssugiura** [comment]
@baduras Good point. I would say it's required, but have chance to discuss with original developer to change the behavior if any request is there. :)

**Comment by baduras** [comment]
If there is a common understanding of the required behavior, I can prepare and submit a patch.

**Comment by ssugiura** [comment]
@baduras Yes, that is very welcome. As starting point, I propose to introduce some option to switch between current behavior and newly introduced so that we won't break existing behavior.

**Comment by ssugiura** [comment]
I will close this issue since the reported behavior is as expected. If further discussion is needed, please reopen this issue. Or please raise PR if any proposal change is available.

**Comment by ssugiura** [comment]
@baduras FYI: After our internal discussion, we decided to introduce new option in logstorage called `MaintainLogstorageLogLevel` to allow clients to overwrite the log level. Details will be followed in upcoming PR.

**Comment by baduras** [comment]
HI @ssugiura, thank you for info. I will check updates.

**Comment by ssugiura** [comment]
@baduras We finally upstreamed our changes (not in master branch yet). Please refer to these commits:
f39242b
ba6f244
