### ISSUE TITLE
dlt-logstorage-ctrl -c 1 -p /mnt/data/dltlog 

### ISSUE THREAD

**Issue by funcode2** [GENIVI/dlt-daemon#242]
Hi, I have downloaded dlt-daemon on my ubuntu and also I have a project that uses dlt-daemon on my ECU. (elina aarch64). 

I run "dlt-logstorage-ctrl -c 1 -p /mnt/data/dltlog" successfully on Ubuntu. But it failed on my ECU. Here is the output from the command "dlt-logstorage-ctrl -c 1 -p /mnt/data/dltlog -v"

<annotation>
root@josh:/mnt/data/dltlog# dlt-logstorage-ctrl -c 1 -p . -v
Logstorage control: Now in verbose mode.
Logstorage control: One shot.
Logstorage common: Now scanning .
Logstorage common: Checking ..
Logstorage common: Checking ...
Logstorage common: Checking dlt_logstorage.conf.
Logstorage common: File found.
Common control: Initializing the connection.
[  501.635235]~DLT~ 5437~INFO     ~Init dlt client struct with default port: 3490.
Logstorage control: event type is [1]    device path is [.]
Logstorage common: Sending event 1 for ..
Logstorage common: Body is now ready.
Common control: Preparing message.
[  501.636135]~DLT~ 5437~INFO     ~dlt_message_init()
Common control: Preparing headers.
Common control: Preparing extra headers.
[  501.636313]~DLT~ 5437~INFO     ~dlt_message_set_extraparameters()
Common control: Ready to receive DLT answers.
[  501.638166]~DLT~ 5437~INFO     ~dlt_message_init()
[  501.638221]~DLT~ 5437~INFO     ~dlt_message_read()
[  501.638248]~DLT~ 5437~INFO     ~dlt_message_get_extraparameters()
[  501.638534]~DLT~ 5437~INFO     ~dlt_message_header_flags()
[  501.638697]~DLT~ 5437~INFO     ~dlt_message_payload()
**Logstorage control: Response received: 'service(3845), error'**
Logstorage control: Response expected: 'service(3845), ok'
[  501.638829]~DLT~ 5437~INFO     ~dlt_message_read()
[  501.638945]~DLT~ 5437~INFO     ~dlt_message_free()
Cleanup dlt client
Logstorage control: Message failed to be send. Please check DLT config.
Logstorage control: Exiting.
</annotation>

The dlt_logstorage.conf is follow:
[FILTER1]
  LogAppName=FLTR
  ContextName=FLTR
  LogLevel=DLT_LOG_INFO
  File=event-log
  FileSize=1000000
  NOFiles=5
  SyncStrategy=ON_DEMAND
  EcuID=ECU1

And the /etc/dlt.conf has the following set up
OfflineLogstorageMaxDevices = 1 (2)    //I tried both, none of them works

Thank you very much for any suggestion, comment. Appreciate.

[dlt.conf.log](https://github.com/GENIVI/dlt-daemon/files/5078261/dlt.conf.log)

Josh

**Comment by funcode2** [comment]
[dlt-logstorage-ctl.log](https://github.com/GENIVI/dlt-daemon/files/5081044/dlt-logstorage-ctl.log)

Sorry, due to the ~ in the log, the previous log pasted in above won't display properly. I have a attached a txt version for easy view.

Thanks
Josh

**Comment by Manojcv55** [comment]
@funcode2   

Please check the applications with App id FLTR is logging dlt logs when dlt-logstorage-ctrl application is started.

**Comment by funcode2** [comment]
Hi Manojcv55,

Thanks for the response. As we see the errors.
**Logstorage control: Response received: 'service(3845), error'** 
Logstorage control: Response expected: 'service(3845), ok' 

There is no log file created. But the dlt-viewer can see the message for App id FLTR.

**Comment by ssugiura** [comment]
@funcode2 At my first glance it failed to connect Logstorage device in dlt-daemon side. Could you send us a dlt-daemon log with log level debug and set Verbose to 1 in `dlt.conf` for better understanding? Thanks.

**Comment by funcode2** [comment]
@ssugiura In my system, the dlt-system dlt-daemon are running as service in the form of daemon. If I stop the service and run dlt-daemon as a standalone application. it seems works fine. 
I modified the enabled Verbose in dlt.conf, but I don't see any log output? can you let me know where to check the log? Thanks

**Comment by ssugiura** [comment]
@funcode2 Then, might be that you're running dlt-daemon as non-root user and the daemon cannot read the configuration file?
For getting the daemon log, you can set `LoggingMode` to 2 (log to file) and modify `LoggingFilename` if needed.

**Comment by funcode2** [comment]
I can see the dlt-daemon log in the file and console. I was confused by the dlt-daemon log and the app output log. Thanks a lot for the suggestion on loggingmode.

Now, I have another questions. At the beginning of start dlt-daemon and start my app. I saw some errors and warnings. What does it mean? Does it matter?
1. Cannot open configuration file.   // what configuration file is referring to?
2. dlt_logstorage_load_config Error : Storing filters failed
3. dlt_daemon_logstorage_setup_internal_storage: Device connect failed
4. dlt_daemon_applications_load: cannot open file /tmp/dlt-runtime-application.cfg: No such file or directory
5.Device already connected. Send disconnect, connect request
6. Entry does not exist in section

Can you please help me to understand the message? Thanks a lot.
[dlt-daemon log.txt](https://github.com/GENIVI/dlt-daemon/files/5165132/dlt-daemon.log.txt)

**Comment by ssugiura** [comment]
@funcode2 Thanks for the logs. 4 and 5 can be ignored for this time. What matters are 1, 2, and 3, as the daemon could not read `dlt_logstorage.conf` under the logstorage device and it couldn't be initialized/connected. So as said above, I assume that you're running daemon as non-root user and trying to connect to the device where daemon doesn't have a permission to access or read to. Can you check on that point?

**Comment by funcode2** [comment]
@ssugiura I agree with you my service is running with difference use/group id that prevents the correct execution of the dlt-logstorage-ctrl. Issue identified and resolved. Thanks a lot.

**Comment by ssugiura** [comment]
I will close this ticket as it seems to be solved. Please reopen or create a new issue if there's anything further.

**Comment by AndyYangjd** [comment]
> @ssugiura I agree with you my service is running with difference use/group id that prevents the correct execution of the dlt-logstorage-ctrl. Issue identified and resolved. Thanks a lot.

Hi， i'm meeting the same issue. Can you plot more details for how to sovle it? Thasnk in advance
