### ISSUE TITLE
Unable to change log level via DLT Viewer if Peristent Storage is enabled.

### ISSUE THREAD

**Issue by cogle** [GENIVI/dlt-daemon#248]
Hello,

I noticed that if I a have enabled persistent storage via a `dlt_logstorage.conf` file that when attempting to change the logging level of an application via the DLT Viewer I am seemingly unable to do so. I was wondering where the code to this logic may be, I am able to change the logging level if I disable the persistent storage, but would possibly like to look into how to enable change log level through the DLT Viewer even if persistent storage is enabled.

**Comment by ssugiura** [comment]
@cogle It is expected that the log level cannot be changed from client if Logstorage is enabled. Please find discussion here: https://github.com/GENIVI/dlt-daemon/issues/236

**Comment by cogle** [comment]
Thanks.

**Comment by ssugiura** [comment]
@cogle  FYI: After our internal discussion, we decided to introduce new option in logstorage called `MaintainLogstorageLogLevel` to allow clients to overwrite the log level. Details will be followed in upcoming PR.

**Comment by cogle** [comment]
Thanks can you please ping me when the PR is available!

**Comment by cogle** [comment]
@ssugiura, sorry to ping you was just wondering if you had a ticket I could track ?
Thanks.

**Comment by ssugiura** [comment]
@cogle Sorry for my late response. Please refer to these commits:
https://github.com/GENIVI/dlt-daemon/pull/279/commits/f39242b20252c55b18437da378adae3b11afeec8
https://github.com/GENIVI/dlt-daemon/pull/279/commits/ba6f24456a1bbc7cf358f4416e18adc34907e90a
