### ISSUE TITLE
DLT log level configuration

### ISSUE THREAD

**Issue by smallert** [GENIVI/dlt-daemon#260]
My current DLT-daemon is version 2.18. In terms of level control, I used dlt-control to change the client's log level and save it. When I execute "dlt-control-o 127.0.0.1" , two configuration files are generated,  namely "dlt-runtime-application.cfg" and "dlt-runtime-context.cfg". But after I restarted DLT-daemon, the saved configuration didn't work, it was the default configuration.
Daemon starts, I found the dlt-daemon will hint "Cannot open a configuration file: /log/cfg/dlt/dlt-runtime.cfg" error log.
But the dlt-runtime.cfg file is not generated.
How can I configure this configuration so that it will still work after the next power recharge?

**Comment by ssugiura** [comment]
@smallert We have also faced the issue and currently working to fix the issue. We are going to upstream the change soon.

**Comment by Damonxy** [comment]
Hi, bro, Do you know what caused this problem？

**Comment by ssugiura** [comment]
@Damonxy There was a commit to change load runtime config function, and this seems to introduce the issue. (c.f. https://github.com/GENIVI/dlt-daemon/commit/da36b5b4fe7a25da4a272618db67601c0f6e3d3a)
We are planning to split the function to initialization and loading of the config.

**Comment by Damonxy** [comment]
respect, bro

**Comment by smallert** [comment]
Thanks for your response.

**Comment by ssugiura** [comment]
@smallert @Damonxy FYI: This should solve the issue: https://github.com/GENIVI/dlt-daemon/pull/279/commits/69536d33fd930adc76226abf56052392fb50da33
