### ISSUE TITLE
dlt-logstorage-ctrl

### ISSUE THREAD

**Issue by smallert** [GENIVI/dlt-daemon#272]
SyncBehavior=ON_SPECIFIC_SIZE,ON_DEMAND
Does the flag ON_DEMAND mean synchronization when a request is received?So how do I make a synchronization request?

**Comment by thanhbnq** [comment]
Hello @smallert ,
dlt-logstorage-ctrl command already supported option "-s" to sync **ON_DEMAND**.
More detailed information could be found when you run "dlt-logstorage-ctrl -h".
I think [the documentation](https://github.com/GENIVI/dlt-daemon/blob/master/doc/dlt-logstorage-ctrl.1.md) should be updated to reflect this option properly.
Best regards,
Thanh

**Comment by smallert** [comment]
Thank you very much. I'll try
