### ISSUE TITLE
Is there a way to get all the applications currently registered with the DLT Daemon

### ISSUE THREAD

**Issue by cogle** [GENIVI/dlt-daemon#276]
I am wondering if there is a way to get all connected clients to the DLT Daemon. I am wanting to have a proxy daemon that monitors all processes that connect to the DLT Daemon and was wondering if there was a function that would list all connected clients to the DLT Daemon.

Thanks.

**Comment by ssugiura** [comment]
@cogle Do you mean clients like DLT Viewer or other command line tools? If so, `daemon_local->pEvent` should keep such kind of information, but unfortunately we don't have specific functions to fulfill the requirement.

**Comment by ssugiura** [comment]
@cogle If you meant by list of applications which is logging to daemon, you can use `-j` option to dlt-control commandline tool to get the list.

**Comment by cogle** [comment]
Thanks, I will look into that!
Another question what happens if two applications with the same application ID happen to connect in different processes?
Will there be any adverse side effects, that are possible ? I have tried this on a limited scale and not noticed anything, but am wondering if there is problem that may occur due to my testing only being small in scale.

**Comment by ssugiura** [comment]
@cogle In principle, the daemon only complains that AppID is duplicated, but logging itself works from both applications. One of the feature which won't work as expected would be sending injection message from clients to application.

**Comment by cogle** [comment]
Thanks again for answering this question!
