### ISSUE TITLE
dlt-receive results in file size 0 if target gets off/restarts

### ISSUE THREAD

**Issue by VipulGrover2** [GENIVI/dlt-daemon#277]
Problem :
I am trying to get the logs from the host using dlt-receive, but doing that I am also running stability test by turning it On/OFF(restarting it)
- So when dlt-receive start collecting the logs, I immediately restart the target Which results in 0 size of data being captured using dlt-receive 

Is there any mechanism :
- terminate the dlt-receive transmission gracefully before it gets restart
- dlt-receive utility have option to write on file multiple times

**Comment by ssugiura** [comment]
@VipulGrover2 Not sure if I got your question correctly, but let me answer them.

>terminate the dlt-receive transmission gracefully before it gets restart
I suppose you mean about signal handler for dlt-receive. The implementation is already available local on our side and will be upstreamed within a week. So you can try to use that.

>dlt-receive utility have option to write on file multiple times
Unfortunately dlt-receive itself doesn't have such option. Instead, you can use Offline Trace or Offline Logstorage feature in dlt-daemon to generate multiple log files on specific size.

**Comment by ssugiura** [comment]
@VipulGrover2 I will close this issue since there is no update for half a year. Please reopen if further discussion is needed.
