### ISSUE TITLE
Copying log files produced by offline log storage

### ISSUE THREAD

**Issue by fmntf** [GENIVI/dlt-daemon#278]
Hello, I wonder if there is a way to copy the log files produced by the offline log storage, while the DLT daemon (hence, log storage) is running.
I mean, I could just copy the files with e.g. `cp /path/to/logstorage/*.dlt /mnt/somewhere`, but what will happen if new logs are received and the curren .dlt file changes during the copy?

Did you think of a way for a safe copy of such logs, without stopping the DLT daemon?

Thank you!
Francesco

**Comment by ssugiura** [comment]
@fmntf You can disconnect logstorage first and then start copying. The relevant command would be `dlt-logstorage-ctrl -c 0 -p /path/to/logstorage`. Then you don't need to stop DLT daemon.

**Comment by ssugiura** [comment]
@fmntf I will close this issue since there is no update for half a year. Please reopen if any further discussion is needed.
