### ISSUE TITLE
Question: How can I create a new line in my DLT message?

### ISSUE THREAD

**Issue by Meldryt** [GENIVI/dlt-daemon#307]
How can i wrap multiple text lines with line breaks into one DLT log call?
I tried something like `DLT_LOG_CXX(context, "HELLO", "\n", "NEW LINE", "\n", "WORLD");`
which didnt work.

**Comment by ssugiura** [comment]
@Meldryt If you want to split them into multiple DLT log messages, then the only way is to call DLT API multiple times as each message requires header and it is generated for each DLT API call.

**Comment by Meldryt** [comment]
okay thank you
