### ISSUE TITLE
Offline logstorage logs content is removed when syncing on demand

### ISSUE THREAD

**Issue by danmardale** [GENIVI/dlt-daemon#31]
Environment:
dlt daemon 2.16.0
dlt viewer 2.18.0 RELEASE
dlt_logstorage.conf stored at PATH:
[FILTER0]
LogAppName=XXXX #(fill in something relevant)
ContextName=XXXX #(fill in something relevant)
LogLevel=DLT_LOG_ERROR
File=filter0
FileSize=20000000
NOFiles=5
#SyncBehavior=ON_DEMAND ON_DAEMON_EXIT
SyncBehavior=ON_MSG

Repro steps:
1. Activate offline logstorage in /etc/dlt.conf and make sure the offline logstorage files are created in PATH.
2. Configure the offline logstorage to create logs with SyncBehavior=ON_MSG.
3. start logging (dlt-logstorage-ctrl -c 1 -p PATH).
4. stop logging (dlt-logstorage-ctrl -c 0 -p PATH). Make sure all the log files  for the filter are created and their size is FileSize.
5. Change the SyncBehavior to ON_DEMAND ON_DAMEON_EXIT
6. start logging (dlt-logstorage-ctrl -c 1 -p PATH).
7. Sync the logs on demand (dlt-logstorage-ctrl - c 1 -p PATH - same path as above).
RESULT: more than one log file size becomes 0 after syncing on demand.

**Comment by clipka** [comment]
Fixed with merged PR #82
