### ISSUE TITLE
CMake, pkg-config: Support #include <dlt.h> and #include <dlt/dlt.h>

### ISSUE THREAD

**Issue by sebastianlipponer** [GENIVI/dlt-daemon#318]
`doc/dlt_for_developers.md` states:

> Please note that the #include statement depends on the means by which you are incorporating the DLT library into your project. The <dlt/dlt.h> form (i.e. with a directory prefix) seen here is necessary when you are using the CMake Config file (see below). If you are using pkg-config instead, then this #include statement needs to refer to only <dlt.h>, due to the way the pkg-config module exports the include directory.

This paragraph completely ignores that code reuse is a common practice. For example, the use of a DLT based code with pkg-config that was previously developed using CMake. This is not easily possible. One has to change the include statement to make the code compile.

This was added in #289. The include statement was previously discussed in #205.

Please consider the exported include path, names and relative locations of the public header files to be a part of the DLT API. The API should not depend on whether one uses pkg-config or CMake since this creates unnecessary integration efforts and hampers code reuse.

Due to this I suggest the following:

* The documentation should state that `#include <dlt/dlt.h>` should be used.
* For backwards compatiblity `#include <dlt.h>` also works, but it's use is deprecated.
* Export both include paths in the pkg-config and CMake config file.

**Comment by ssugiura** [comment]
@sebastianlipponer Thanks for raising this concern.
We discussed about this with author before so I'd like to involve @mawillers here too.
Ref: https://github.com/GENIVI/dlt-daemon/pull/289#discussion_r602529048
@mawillers Any suggestions?

**Comment by mawillers** [comment]
We could add the "new style" to the *.pc file in addition to the "legacy style". See #319 for an implementation of that.

I would suggest to keep the CMake file clean in this regard and only support the "new style".

**Comment by sebastianlipponer** [comment]
Yes, but this not sufficient to avoid problems. CMake must also export the legacy include path in addition. See my comment in #319.

**Comment by mawillers** [comment]
I'd really prefer to not clutter the build system with unnecessary include paths. Clearly, the "new-style" approach is preferable and should be used. Anyone with a large existing code base who might refuse to convert all her #include statements to new-style has obviously been using pkg-config so far (or maybe an own CMake Find module) and can continue to use that without any disadvantages.

Anyone else, i.e. people writing new libdlt-using code, should use the new-style approach and can then choose between pkg-config and CMake.
What's not to like with this approach? :-)

I'll add a change to the documentation shortly.

**Comment by sebastianlipponer** [comment]
I don't see how an additional include path can possibly clutter a build system. If you have real technical arguments then please state them. This additional include path is not unnecessary. It ensures consistency between pkg-config and CMake files. That is it ensures that code works independent from which build system integration is being used.

A DLT code is often compiled and used with different dlt-daemon releases. I cannot just migrate all the include statements of a code to the new-style because this breaks its usage with an older release using pkg-config. Conversely, I cannot leave the include statements as-is when I want to compile the code with a more recent release using CMake.

As I stated earlier, please consider the exported include path, names and relative locations of the public header files to be a part of the dlt-daemon API. If you want to change the API in a backwards incompatible way then please do this in the next major release. Until then please export include paths consistently in the supported build system integration files.

**Comment by mawillers** [comment]
The breakage occurs when people have another header file called dlt.h on their system. I have such a thing on my system, coming from a "Direct Linear Transformation" library. With `<prefix>/dlt/` being injected into my compiler's include search path, there would be a conflict, as the toolchain might find either `/usr/include/dlt/dlt.h` or `/usr/include/dlt.h`, depending on toolchain-internal behavior.

> If you want to change the API in a backwards incompatible way then please do this in the next major release.

Or: if you want to switch to the provided CMake Config file, consider that a breaking change. If you want to avoid that, stay with the pkg-config module. :-)

**Comment by sebastianlipponer** [comment]
AFAIK a standard compliant toolchain searches include paths in the given order. So you should be able to solve this by rearranging the order. Obviously, using `#include <dlt.h>` for both libraries does not work. So I would assume that you attempt to use `#include <dlt.h>` for the "Direct Linear Transformation" library and `#include <dlt/dlt.h>` for dlt-daemon. I guess using `/usr/include`, `/usr/include/dlt` in this order should make this work, i.e. just add `/usr/include` before the DLT include paths.

Btw, where can I find this library? [Debian does not know this header](https://packages.debian.org/search?searchon=contents&keywords=%2Fusr%2Finclude%2Fdlt.h&mode=path&suite=stable&arch=any). Moreover, I was not able to find existing issues related to clashing header files. So I am inclined to think that this issue is not very relevant to others whereas a consistent behavior of pkg-config and CMake files is relevant to many DLT users.

**Comment by mawillers** [comment]
There is no "standard compliant toolchain", as the C/C++ standard does not place any meaningful requirements on this topic. There is e.g. §16.2-2 in the C++14 standard:

> [An #include directive] searches a sequence of implementation-defined places for a header identified uniquely by the specified sequence between the < and > delimiters, and causes the replacement of that directive by the entire contents of the header. How the places are specified or the header identified is implementation-defined.

and pretty much the same for the "..." form, except that it falls back to the <...> form if not supported or no match was found.

There is nothing about any -I flags, of course, because that's entirely compiler-specific. And while e.g. gcc will likely (though a lot can be configured here at build-time of gcc) search the various -I flags in the given order, you just don't know in what sequence your build system conglomerate (CMake, Conan, Vcpkg, meson, …) will present it to gcc.

That library is an in-house on, so you won't find it in Debian, of course. That doesn't make it less painful.

**Comment by sebastianlipponer** [comment]
This whole discussion boils down to that you are effectively asking to keep the DLT pkg-config and CMake files intentionally inconsistent at the expense of many DLT users only to facilitate you with the integration of a weird in-house code.

I suggest to change the in-house code. I think it's a bad design decision to use the same include directive as a popular open-source code contained in many different Linux distributions. Especially if you want to use both in the same code.
