### ISSUE TITLE
Improvement to be done on dlt internal buffer allocation logic

### ISSUE THREAD

**Issue by anoojgopi** [GENIVI/dlt-daemon#37]
Currently we the allocation/de-allocation logic does unneccessary memory copy causing CPU load and on top we need double the heap size than it actually requires in usual cases.

Let's say we configure the dlt buffer size as 20 MB, we need approx 40 MB during the allocation of the final step size.

Same logic is used in dltlib, this all applications are also affected due to this inefficient logic.

We need to improve it.

**Comment by ssugiura** [comment]
@anoojgopi Sorry that we haven't replied to your request for long time. The allocation/deallocation should only happen in rare cases; the daemon is not alive yet, some issues in socket/fifo buffers, too much logging happening, etc. If it is happening often for a specific dlt-user, the application should be configured with the env variables in a way that it does not happen anymore:
```
DLT_USER_BUFFER_MAX
DLT_USER_BUFFER_MIN
DLT_USER_BUFFER_STEP
```
If you have any further request, please reopen this issue again.
