### ISSUE TITLE
DLT-viewer : Serial connection is not working for Ubuntu in Virtual Machine

### ISSUE THREAD

**Issue by mahendrankk** [GENIVI/dlt-daemon#56]
Use DLT Viewer v2.18 in Ubuntu. Connect ECU in Serial Mode over COM port. Connection is not established.
Note: Minicom working properly in Ubuntu VM and also there is no issue in windows version of same Dlt-viewer.

**Comment by clipka** [comment]
If this is a DLT-Viewer issue, it should be filed in dlt-viewer repository. If you think it is related to the daemon, please describe a bit more in detail your observations.

**Comment by mahendrankk** [comment]
@clipka 
Yes, the issue is related to DLT-viewer usage but root cause is '$USER was not part of dialout group' on ubuntu settings.
by executing "sudo usermod -a -G dialout $USER" , issue was solved. 
So, I'm closing PR #56 issue
