### ISSUE TITLE
unnecessary reference to zlib in .pc file

### ISSUE THREAD

**Issue by kdopen** [GENIVI/dlt-daemon#76]
automotive-dlt.pc.in specifies "-lz" in it's Libs line regardless of whether or not WITH_DLT_SYSTEM is set to OFF.

When building under versions of Yocto newer than Pyro (i.e. those with recipe-specific sysroots) this causes clients of the daemon to fail to link unless zlib is ALWAYS present in the DEPENDS line of themselves or of the dlt-daemon recipe.

**Comment by clipka** [comment]
Should be fixed with #91 (commit: fecd1ccc6da327ae846db9a6feac7917120c99ac)
