### ISSUE TITLE
Query: When is the next release planned ?

### ISSUE THREAD

**Issue by avinash-palleti** [GENIVI/dlt-daemon#78]
Hi,

When  is the next release planned which includes all the fixes post v.2.17.0 release.

**Comment by anitha-suresh** [comment]
@clipka : Could you please let us know on the next release, in case you have planned on it.

**Comment by clipka** [comment]
Sorry for late reply. We currently want to push some more code before creating the next release. Latest end of the year the next release should be available.

**Comment by clipka** [comment]
Today :)
