### ISSUE TITLE
Dead links in several files

### ISSUE THREAD

**Issue by clipka** [GENIVI/dlt-daemon#79]
There are a lot of dead links in doc/ directory (and most likely others, too). Those should be updated or removed.

**Comment by clipka** [comment]
I have reworked parts of the documentation to be readable directly inside github. @gunnarx : Please have a look. Thanks.

**Comment by gunnarx** [comment]
Looks good now and I note that you have provided the relevant information in the README (mailing list, how to contribute, where to file bugs, coding rules, ...).  If CI and static analysis is added I think every part of the Q&M policy will be fulfilled.  One step at a time. :)

**Comment by clipka** [comment]
OK, then let's close this one.
