### ISSUE TITLE
Question: How can i print line number with all dlt logs? 

### ISSUE THREAD

**Issue by saumilsdk** [GENIVI/dlt-daemon#83]
I want to print file name along with line number wherever i put info/debug/error without changing any of the code. Is this possible?

**Comment by ManikandanChockalingam** [comment]
do you mean __LINE__ , __FILE__ kind of implementation?

**Comment by saumilsdk** [comment]
Yes that correct. Basically I was looking similar to TIMESTAMP, FILE_NAME, LINE NUMBER, LOG LEVEL, LOG MESSAGE

**Comment by ManikandanChockalingam** [comment]
Without changing code, its not possible to get file name and line number. You have to add those macro's as an additional argument to the DLT_LOG. If you are using a wrapper for DLT_LOG then its much easier to change just in one place.

**Comment by saumilsdk** [comment]
@ManikandanChockalingam If you have done this, can you please paste the code? I am not much familiar with this much.

**Comment by saumilsdk** [comment]
Thanks :)
