### ISSUE TITLE
'sd_booted' undefined reference - compiler/linker problem for systemd + tests

### ISSUE THREAD

**Issue by jardous** [GENIVI/dlt-daemon#98]
There is a compilation/linker problem wen trying to compile with systemd and tests enabled:

$ cmake -DWITH_DLT_TESTS=ON -DWITH_TESTSCRIPTS=ON -DWITH_DLT_UNIT_TESTS=ON -DWITH_SYSTEMD=ON -DWITH_SYSTEMD_JOURNAL=ON CMakeLists.txt

Error output:

[ 93%] Building CXX object tests/CMakeFiles/gtest_dlt_daemon_gateway.dir/gtest_dlt_daemon_gateway.cpp.o
[ 94%] Linking CXX executable gtest_dlt_daemon_gateway
../src/daemon/libdlt_daemon.so: undefined reference to `sd_booted'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/gtest_dlt_daemon_gateway] Error 1
make[1]: *** [tests/CMakeFiles/gtest_dlt_daemon_gateway.dir/all] Error 2
make: *** [all] Error 2

**Comment by clipka** [comment]
@jardous , I guess this can be closed now?
